version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/permissions.sh
      timeout: 300
      runas: root
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root
